### ISSUE TITLE
Search on gender using lowercase is not working. (Search on tokens should not be case sensitive https://www.hl7.org/fhir/search.html#token)

### ISSUE THREAD

**Issue by markodukic** [nhsconnect/careconnect-reference-implementation#12] opened 2017-10-13 09:17 UTC
http://194.189.27.193/careconnect/STU3/Patient?gender=male

Expected 51 patients.

Received 200-OK no patients.

Are codes case insensitive?

**Comment by KevinMayfield** [comment] 2017-10-14 05:17
duplicate of #1

**Comment by KevinMayfield** [comment] 2017-10-14 05:18
https://github.com/nhsconnect/careconnect-reference-implementation/issues/1

**Comment by KevinMayfield** [comment] 2017-10-14 05:18
https://github.com/nhsconnect/careconnect-reference-implementation/issues/12

**Comment by KevinMayfield** [comment] 2017-10-14 05:19
Duplicate of issue 3 https://github.com/nhsconnect/careconnect-reference-implementation/issues/3

**Closed as completed by KevinMayfield** 2017-10-14 05:19 UTC
